### ISSUE TITLE
Hola/Dialect tree directions and grouped nodes

### ISSUE THREAD

**Issue by Timmmm** [mjwybrow/adaptagrams#48]
I'm trying to make a very large org chart diagram which is just a simple tree. I thought I'd try HOLA/Dialect because the examples look great, but sadly it just gives me the same results as Graphviz - a really really wide tree that's impossible to read:

![image](https://user-images.githubusercontent.com/376842/115081627-84afe800-9efc-11eb-8396-582521190a70.png)

It's a very wide flat tree so it's not exactly wrong, but I have some ideas for improvement.

1. It could change the tree direction at each node. Especially at the root node, the CEO's immediate reports could be placed in trees going west, north and east. That would help make the whole thing squarer.
2. Each person's reports could be grouped in a box, and then placed in a grid.

Sort of like this:

![image](https://user-images.githubusercontent.com/376842/115082314-a2ca1800-9efd-11eb-8fa7-640e5935b2a5.png)

Is any of that possible with Dialect?

**Comment by skieffer** [comment]
Hi, Tim. Glad you liked examples of HOLA layouts. A few thoughts:

* You could "trick" HOLA by making your graph not actually a tree. Take any node V for which you want to see trees radiating out from it in all four compass directions, and replace V with _four_ nodes V1, V2, V3, V4, all linked together in a little ring. Then divvy up the original neighbors of V into four sets of neighbors, linking them to the Vi as you see fit. Will this produce great results? I don't know, but it could be interesting.

(This almost sounds like sth that could be an interesting built-in option in libdialect -- i.e. to have it turn certain nodes into "rings" for you, then restore them after computing the layout -- but unfortunately it's not in there at this time.)

* As a completely separate alternative, it almost sounds like you want a radial layout. I think yFiles / yEd has that. Could be worth a try.

* Even just a pure stress-minimizing layout would tend to do a more radial layout.

* Of course dynamic layout (expanding / collapsing parts of the tree) could do great things, but that's a whole other story... not supported in libdialect out of the box by any means.

**Comment by Timmmm** [comment]
Hmm, I tried removing the root node and making its children into a ring. Sooort of worked, but it's looking like I need to write a custom layout algorithm.

![image](https://user-images.githubusercontent.com/376842/115389953-9f70ae00-a1d5-11eb-96b0-330e679e38c1.png)

Thanks for the suggestions!

**Comment by skieffer** [comment]
Aha. Interesting. I wonder if it would improve if you continued applying this trick recursively. E.g. for the giant tree on the bottom of the image, the root node appears to have 7 children. Maybe make _them_ into a ring attached to that root node, etc. etc. Whether this would really be producing what you want, I don't know, and of course at some point there's the question of whether this is more work than writing your own algorithm!

Also in the realm of changing the graph rather than the algorithm: It seems like much of the width in this graph comes from large sets of leaf nodes all sharing a common parent. Can you replace sibling leaves with a single node, with a vertical list of labels on it instead? Just a thought.

Good luck.

**Comment by Timmmm** [comment]
Yeah the vertical list is a great idea - I found found [this demo](https://gojs.net/latest/samples/orgChartStatic.html) that does it like that and it seems reasonable. Thanks for the help!
